/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package extrabonoloto;

import java.util.ArrayList;
import java.util.Random;



/**
 *
 * @author cromerofajar
 */
public class BonolotoPaleta extends javax.swing.JFrame {
    ArrayList <Integer> tuserie=new ArrayList<Integer>();
    ArrayList <Integer> serieganadora=new ArrayList<Integer>();
    ArrayList <Integer> serieganadora2=new ArrayList<Integer>();
    int aciertos;
    /**
     * Creates new form BonolotoPaleta
     */
    public BonolotoPaleta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        n1 = new javax.swing.JButton();
        n2 = new javax.swing.JButton();
        n3 = new javax.swing.JButton();
        n4 = new javax.swing.JButton();
        n5 = new javax.swing.JButton();
        n6 = new javax.swing.JButton();
        n7 = new javax.swing.JButton();
        n8 = new javax.swing.JButton();
        n9 = new javax.swing.JButton();
        n10 = new javax.swing.JButton();
        n11 = new javax.swing.JButton();
        n12 = new javax.swing.JButton();
        n13 = new javax.swing.JButton();
        n14 = new javax.swing.JButton();
        n15 = new javax.swing.JButton();
        n16 = new javax.swing.JButton();
        n17 = new javax.swing.JButton();
        n18 = new javax.swing.JButton();
        n19 = new javax.swing.JButton();
        n20 = new javax.swing.JButton();
        n21 = new javax.swing.JButton();
        n22 = new javax.swing.JButton();
        n23 = new javax.swing.JButton();
        n24 = new javax.swing.JButton();
        n25 = new javax.swing.JButton();
        n26 = new javax.swing.JButton();
        n27 = new javax.swing.JButton();
        n28 = new javax.swing.JButton();
        n29 = new javax.swing.JButton();
        n30 = new javax.swing.JButton();
        n31 = new javax.swing.JButton();
        n32 = new javax.swing.JButton();
        n33 = new javax.swing.JButton();
        n34 = new javax.swing.JButton();
        n35 = new javax.swing.JButton();
        n36 = new javax.swing.JButton();
        n37 = new javax.swing.JButton();
        n38 = new javax.swing.JButton();
        n39 = new javax.swing.JButton();
        n40 = new javax.swing.JButton();
        n41 = new javax.swing.JButton();
        n42 = new javax.swing.JButton();
        n43 = new javax.swing.JButton();
        n44 = new javax.swing.JButton();
        n45 = new javax.swing.JButton();
        n46 = new javax.swing.JButton();
        n47 = new javax.swing.JButton();
        n48 = new javax.swing.JButton();
        n49 = new javax.swing.JButton();
        cuadroTuSerie = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cuadroSerieGanadora = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cuadroSerieAcertados = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        borrar = new javax.swing.JButton();
        confirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        n1.setText("1");
        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });

        n2.setText("2");
        n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2ActionPerformed(evt);
            }
        });

        n3.setText("3");
        n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n3ActionPerformed(evt);
            }
        });

        n4.setText("4");
        n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n4ActionPerformed(evt);
            }
        });

        n5.setText("5");
        n5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n5ActionPerformed(evt);
            }
        });

        n6.setText("6");
        n6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n6ActionPerformed(evt);
            }
        });

        n7.setText("7");
        n7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n7ActionPerformed(evt);
            }
        });

        n8.setText("8");
        n8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n8ActionPerformed(evt);
            }
        });

        n9.setText("9");
        n9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n9ActionPerformed(evt);
            }
        });

        n10.setText("10");
        n10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n10ActionPerformed(evt);
            }
        });

        n11.setText("11");
        n11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n11ActionPerformed(evt);
            }
        });

        n12.setText("12");
        n12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n12ActionPerformed(evt);
            }
        });

        n13.setText("13");
        n13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n13ActionPerformed(evt);
            }
        });

        n14.setText("14");
        n14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n14ActionPerformed(evt);
            }
        });

        n15.setText("15");
        n15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n15ActionPerformed(evt);
            }
        });

        n16.setText("16");
        n16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n16ActionPerformed(evt);
            }
        });

        n17.setText("17");
        n17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n17ActionPerformed(evt);
            }
        });

        n18.setText("18");
        n18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n18ActionPerformed(evt);
            }
        });

        n19.setText("19");
        n19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n19ActionPerformed(evt);
            }
        });

        n20.setText("20");
        n20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n20ActionPerformed(evt);
            }
        });

        n21.setText("21");
        n21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n21ActionPerformed(evt);
            }
        });

        n22.setText("22");
        n22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n22ActionPerformed(evt);
            }
        });

        n23.setText("23");
        n23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n23ActionPerformed(evt);
            }
        });

        n24.setText("24");
        n24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n24ActionPerformed(evt);
            }
        });

        n25.setText("25");
        n25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n25ActionPerformed(evt);
            }
        });

        n26.setText("26");
        n26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n26ActionPerformed(evt);
            }
        });

        n27.setText("27");
        n27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n27ActionPerformed(evt);
            }
        });

        n28.setText("28");
        n28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n28ActionPerformed(evt);
            }
        });

        n29.setText("29");
        n29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n29ActionPerformed(evt);
            }
        });

        n30.setText("30");
        n30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n30ActionPerformed(evt);
            }
        });

        n31.setText("31");
        n31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n31ActionPerformed(evt);
            }
        });

        n32.setText("32");
        n32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n32ActionPerformed(evt);
            }
        });

        n33.setText("33");
        n33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n33ActionPerformed(evt);
            }
        });

        n34.setText("34");
        n34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n34ActionPerformed(evt);
            }
        });

        n35.setText("35");
        n35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n35ActionPerformed(evt);
            }
        });

        n36.setText("36");
        n36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n36ActionPerformed(evt);
            }
        });

        n37.setText("37");
        n37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n37ActionPerformed(evt);
            }
        });

        n38.setText("38");
        n38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n38ActionPerformed(evt);
            }
        });

        n39.setText("39");
        n39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n39ActionPerformed(evt);
            }
        });

        n40.setText("40");
        n40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n40ActionPerformed(evt);
            }
        });

        n41.setText("41");
        n41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n41ActionPerformed(evt);
            }
        });

        n42.setText("42");
        n42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n42ActionPerformed(evt);
            }
        });

        n43.setText("43");
        n43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n43ActionPerformed(evt);
            }
        });

        n44.setText("44");
        n44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n44ActionPerformed(evt);
            }
        });

        n45.setText("45");
        n45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n45ActionPerformed(evt);
            }
        });

        n46.setText("46");
        n46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n46ActionPerformed(evt);
            }
        });

        n47.setText("47");
        n47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n47ActionPerformed(evt);
            }
        });

        n48.setText("48");
        n48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n48ActionPerformed(evt);
            }
        });

        n49.setText("49");
        n49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n49ActionPerformed(evt);
            }
        });

        cuadroTuSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroTuSerieActionPerformed(evt);
            }
        });

        jLabel1.setText("Tu Serie");

        cuadroSerieGanadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroSerieGanadoraActionPerformed(evt);
            }
        });

        jLabel2.setText("Serie ganadora");

        cuadroSerieAcertados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroSerieAcertadosActionPerformed(evt);
            }
        });

        jLabel3.setText("Acertados");

        borrar.setText("BORRAR TU SERIE");
        borrar.setEnabled(false);
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        confirmar.setText("CONFIRMAR BOLETO");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(n36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(n15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(n29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n34))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(n22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n27)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n28)
                            .addComponent(n35)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(n8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(n1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(n10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(n12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(n5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(n43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cuadroTuSerie, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(cuadroSerieAcertados)
                            .addComponent(cuadroSerieGanadora))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(cuadroTuSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadroSerieGanadora, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cuadroSerieAcertados, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n1)
                    .addComponent(n3)
                    .addComponent(n4)
                    .addComponent(n5)
                    .addComponent(n6)
                    .addComponent(n7)
                    .addComponent(n2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n8)
                    .addComponent(n9)
                    .addComponent(n11)
                    .addComponent(n12)
                    .addComponent(n13)
                    .addComponent(n14)
                    .addComponent(n10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n15)
                    .addComponent(n16)
                    .addComponent(n17)
                    .addComponent(n18)
                    .addComponent(n19)
                    .addComponent(n20)
                    .addComponent(n21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n22)
                    .addComponent(n23)
                    .addComponent(n24)
                    .addComponent(n25)
                    .addComponent(n26)
                    .addComponent(n27)
                    .addComponent(n28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n29)
                    .addComponent(n30)
                    .addComponent(n31)
                    .addComponent(n32)
                    .addComponent(n33)
                    .addComponent(n34)
                    .addComponent(n35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n36)
                    .addComponent(n37)
                    .addComponent(n38)
                    .addComponent(n39)
                    .addComponent(n40)
                    .addComponent(n41)
                    .addComponent(n42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n43)
                    .addComponent(n44)
                    .addComponent(n45)
                    .addComponent(n46)
                    .addComponent(n47)
                    .addComponent(n48)
                    .addComponent(n49))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrar)
                    .addComponent(confirmar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void n6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n6ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"6 ");
        tuserie.add(6);
        n6.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n6ActionPerformed

    private void cuadroTuSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroTuSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroTuSerieActionPerformed

    private void cuadroSerieGanadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroSerieGanadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroSerieGanadoraActionPerformed

    private void cuadroSerieAcertadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroSerieAcertadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroSerieAcertadosActionPerformed

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"1 ");
        tuserie.add(1);
        n1.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n1ActionPerformed

    private void n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"2 ");
        tuserie.add(2);
        n2.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n2ActionPerformed

    private void n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n3ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"3 ");
        tuserie.add(3);
        n3.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n3ActionPerformed

    private void n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n4ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"4 ");
        tuserie.add(4);
        n4.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n4ActionPerformed

    private void n5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n5ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"5 ");
        tuserie.add(5);
        n5.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n5ActionPerformed

    private void n7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n7ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"7 ");
        tuserie.add(7);
        n7.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n7ActionPerformed

    private void n8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n8ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"8 ");
        tuserie.add(8);
        n8.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n8ActionPerformed

    private void n9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n9ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"9 ");
        tuserie.add(9);
        n9.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n9ActionPerformed

    private void n10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n10ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"10 ");
        tuserie.add(10);
        n10.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n10ActionPerformed

    private void n11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n11ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"11 ");
        tuserie.add(11);
        n11.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n11ActionPerformed

    private void n12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n12ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"12 ");
        tuserie.add(12);
        n12.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n12ActionPerformed

    private void n13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n13ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"13 ");
        tuserie.add(13);
        n13.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n13ActionPerformed

    private void n14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n14ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"14 ");
        tuserie.add(14);
        n14.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n14ActionPerformed

    private void n15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n15ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"15 ");
        tuserie.add(15);
        n15.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n15ActionPerformed

    private void n16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n16ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"16 ");
        tuserie.add(16);
        n16.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n16ActionPerformed

    private void n17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n17ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"17 ");
        tuserie.add(17);
        n17.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n17ActionPerformed

    private void n18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n18ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"18 ");
        tuserie.add(18);
        n18.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n18ActionPerformed

    private void n19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n19ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"19 ");
        tuserie.add(19);
        n19.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n19ActionPerformed

    private void n20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n20ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"20 ");
        tuserie.add(20);
        n20.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n20ActionPerformed

    private void n21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n21ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"21 ");
        tuserie.add(21);
        n21.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n21ActionPerformed

    private void n22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n22ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"22 ");
        tuserie.add(22);
        n22.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n22ActionPerformed

    private void n23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n23ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"23 ");
        tuserie.add(23);
        n23.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n23ActionPerformed

    private void n24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n24ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"24 ");
        tuserie.add(24);
        n24.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n24ActionPerformed

    private void n25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n25ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"25 ");
        tuserie.add(25);
        n25.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n25ActionPerformed

    private void n26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n26ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"26 ");
        tuserie.add(26);
        n26.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n26ActionPerformed

    private void n27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n27ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"27 ");
        tuserie.add(27);
        n27.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n27ActionPerformed

    private void n28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n28ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"28 ");
        tuserie.add(20);
        n28.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n28ActionPerformed

    private void n29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n29ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"29 ");
        tuserie.add(29);
        n29.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n29ActionPerformed

    private void n30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n30ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"30 ");
        tuserie.add(30);
        n30.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n30ActionPerformed

    private void n31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n31ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"31 ");
        tuserie.add(31);
        n31.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n31ActionPerformed

    private void n32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n32ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"32 ");
        tuserie.add(32);
        n32.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n32ActionPerformed

    private void n33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n33ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"33 ");
        tuserie.add(33);
        n33.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n33ActionPerformed

    private void n34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n34ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"34 ");
        tuserie.add(34);
        n34.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n34ActionPerformed

    private void n35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n35ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"35 ");
        tuserie.add(35);
        n35.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n35ActionPerformed

    private void n36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n36ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"36 ");
        tuserie.add(36);
        n36.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n36ActionPerformed

    private void n37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n37ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"37 ");
        tuserie.add(37);
        n37.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n37ActionPerformed

    private void n38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n38ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"38 ");
        tuserie.add(38);
        n38.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n38ActionPerformed

    private void n39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n39ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"39 ");
        tuserie.add(39);
        n39.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n39ActionPerformed

    private void n40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n40ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"40 ");
        tuserie.add(40);
        n40.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n40ActionPerformed

    private void n41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n41ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"41 ");
        tuserie.add(41);
        n41.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n41ActionPerformed

    private void n42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n42ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"42 ");
        tuserie.add(42);
        n42.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n42ActionPerformed

    private void n43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n43ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"43 ");
        tuserie.add(43);
        n43.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n43ActionPerformed

    private void n44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n44ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"44 ");
        tuserie.add(44);
        n44.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n44ActionPerformed

    private void n45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n45ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"45 ");
        tuserie.add(45);
        n45.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n45ActionPerformed

    private void n46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n46ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"46 ");
        tuserie.add(46);
        n46.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n46ActionPerformed

    private void n47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n47ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"47 ");
        tuserie.add(47);
        n47.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n47ActionPerformed

    private void n48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n48ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"48 ");
        tuserie.add(48);
        n48.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n48ActionPerformed

    private void n49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n49ActionPerformed
        if(tuserie.size()==6){
            
        }else{
        cuadroTuSerie.setText(cuadroTuSerie.getText()+"49 ");
        tuserie.add(49);
        n49.setEnabled(false);
        borrar.setEnabled(true);
        }
    }//GEN-LAST:event_n49ActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        for(int i=0;i>tuserie.size();i++){
            tuserie.remove(i);
        }
        tuserie=new ArrayList<Integer>();
        borrar.setEnabled(false);
        cuadroTuSerie.setText("");
        n1.setEnabled(true);n2.setEnabled(true);n3.setEnabled(true);n4.setEnabled(true);n5.setEnabled(true);n6.setEnabled(true);n7.setEnabled(true);
        n8.setEnabled(true);n9.setEnabled(true);n10.setEnabled(true);n11.setEnabled(true);n12.setEnabled(true);n13.setEnabled(true);n14.setEnabled(true);
        n15.setEnabled(true);n16.setEnabled(true);n17.setEnabled(true);n18.setEnabled(true);n19.setEnabled(true);n20.setEnabled(true);n21.setEnabled(true);
        n22.setEnabled(true);n23.setEnabled(true);n24.setEnabled(true);n25.setEnabled(true);n26.setEnabled(true);n27.setEnabled(true);n28.setEnabled(true);
        n29.setEnabled(true);n30.setEnabled(true);n31.setEnabled(true);n32.setEnabled(true);n33.setEnabled(true);n34.setEnabled(true);n35.setEnabled(true);
        n36.setEnabled(true);n37.setEnabled(true);n38.setEnabled(true);n39.setEnabled(true);n40.setEnabled(true);n41.setEnabled(true);n42.setEnabled(true);
        n43.setEnabled(true);n44.setEnabled(true);n45.setEnabled(true);n46.setEnabled(true);n47.setEnabled(true);n48.setEnabled(true);n49.setEnabled(true);
    }//GEN-LAST:event_borrarActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        int tope=5;
        cuadroSerieAcertados.setText("");
        cuadroSerieGanadora.setText("");
        int numero,aciertos=0;
        Random r=new Random();
        for(int i=0;i<=tope;i++){
        numero=r.nextInt(48)+1;
        if(serieganadora.isEmpty()!=true){
            
                if(serieganadora2.contains(numero)){
                    i--;
                }else{
                    serieganadora.add(numero);
                    cuadroSerieGanadora.setText(cuadroSerieGanadora.getText()+numero+" ");
                }
            
            serieganadora2.add(numero);
            
        }
        else{
            serieganadora.add(numero);
            serieganadora2.add(numero);
            cuadroSerieGanadora.setText(numero+" ");
        }
        }
        for(Integer serie:tuserie){
            if(serieganadora.contains(serie)){
                aciertos++;
            }
        }
        cuadroSerieAcertados.setText(aciertos+"");
        aciertos=0;
        serieganadora.removeAll(serieganadora);
        serieganadora2.removeAll(serieganadora2);
        n1.setEnabled(true);n2.setEnabled(true);n3.setEnabled(true);n4.setEnabled(true);n5.setEnabled(true);n6.setEnabled(true);n7.setEnabled(true);
        n8.setEnabled(true);n9.setEnabled(true);n10.setEnabled(true);n11.setEnabled(true);n12.setEnabled(true);n13.setEnabled(true);n14.setEnabled(true);
        n15.setEnabled(true);n16.setEnabled(true);n17.setEnabled(true);n18.setEnabled(true);n19.setEnabled(true);n20.setEnabled(true);n21.setEnabled(true);
        n22.setEnabled(true);n23.setEnabled(true);n24.setEnabled(true);n25.setEnabled(true);n26.setEnabled(true);n27.setEnabled(true);n28.setEnabled(true);
        n29.setEnabled(true);n30.setEnabled(true);n31.setEnabled(true);n32.setEnabled(true);n33.setEnabled(true);n34.setEnabled(true);n35.setEnabled(true);
        n36.setEnabled(true);n37.setEnabled(true);n38.setEnabled(true);n39.setEnabled(true);n40.setEnabled(true);n41.setEnabled(true);n42.setEnabled(true);
        n43.setEnabled(true);n44.setEnabled(true);n45.setEnabled(true);n46.setEnabled(true);n47.setEnabled(true);n48.setEnabled(true);n49.setEnabled(true);
    }//GEN-LAST:event_confirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BonolotoPaleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BonolotoPaleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BonolotoPaleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BonolotoPaleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BonolotoPaleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JButton confirmar;
    private javax.swing.JTextField cuadroSerieAcertados;
    private javax.swing.JTextField cuadroSerieGanadora;
    private javax.swing.JTextField cuadroTuSerie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton n1;
    private javax.swing.JButton n10;
    private javax.swing.JButton n11;
    private javax.swing.JButton n12;
    private javax.swing.JButton n13;
    private javax.swing.JButton n14;
    private javax.swing.JButton n15;
    private javax.swing.JButton n16;
    private javax.swing.JButton n17;
    private javax.swing.JButton n18;
    private javax.swing.JButton n19;
    private javax.swing.JButton n2;
    private javax.swing.JButton n20;
    private javax.swing.JButton n21;
    private javax.swing.JButton n22;
    private javax.swing.JButton n23;
    private javax.swing.JButton n24;
    private javax.swing.JButton n25;
    private javax.swing.JButton n26;
    private javax.swing.JButton n27;
    private javax.swing.JButton n28;
    private javax.swing.JButton n29;
    private javax.swing.JButton n3;
    private javax.swing.JButton n30;
    private javax.swing.JButton n31;
    private javax.swing.JButton n32;
    private javax.swing.JButton n33;
    private javax.swing.JButton n34;
    private javax.swing.JButton n35;
    private javax.swing.JButton n36;
    private javax.swing.JButton n37;
    private javax.swing.JButton n38;
    private javax.swing.JButton n39;
    private javax.swing.JButton n4;
    private javax.swing.JButton n40;
    private javax.swing.JButton n41;
    private javax.swing.JButton n42;
    private javax.swing.JButton n43;
    private javax.swing.JButton n44;
    private javax.swing.JButton n45;
    private javax.swing.JButton n46;
    private javax.swing.JButton n47;
    private javax.swing.JButton n48;
    private javax.swing.JButton n49;
    private javax.swing.JButton n5;
    private javax.swing.JButton n6;
    private javax.swing.JButton n7;
    private javax.swing.JButton n8;
    private javax.swing.JButton n9;
    // End of variables declaration//GEN-END:variables
}
